export enum AppPath {
  Products = '/products',
  Home = '/home',
  Orders = '/orders',
  Settings = '/settings',
  Root = '/',
  AddProduct = '/products/add-product',
  AddRecipe = '/products/add-recipe',
  ProductOverview = '/products/overview',
  Inventory = '/products/inventory',
  ViewProduct = '/products/:id',
  ViewRecipe = '/recipes/:id',
  Recipe = '/recipes',
  RecipeOverview = '/product/recipes/overview',
  Profile = '/profile',
  Store = '/store',
  Staff = '/staff',
  Error = '/error',
}
