export enum AppPath {
  Products = '/products',
  Home = '/home',
  Orders = '/orders',
  Settings = '/settings',
  Root = '/',
  AddProduct = '/products/add-product',
  ProductOverview = '/products/overview',
  ProductList = '/products/list',
  ViewProduct = '/products/:id',
  Recipe = '/recipe',
  RecipeOverview = '/product/recipe',
  Profile = '/profile',
  Store = '/store',
  Error = '/error',
}
